version: "3"

services:
    mysql:
        image: mysql:8.4.0
        container_name: mysql_wordpress
        tty: true
        ports:
            - "4208:3306"
        volumes:
            - "./var/libclea/mysql/:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: wordpress
            MYSQL_USER: miusuario
            MYSQL_PASSWORD: mipassword
        networks:
            - wordpress_mysql_network

    server:
        image: wordpress:6.5.4
        container_name: wordpress-6.5.4
        ports:
            - "4282:80"
        volumes:
            - "./var/www/html/:/var/www/html"
        environment:
            WORDPRESS_DB_USER: miusuario
            WORDPRESS_DB_PASSWORD: mipassword
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_HOST: mysql_wordpress
        depends_on:
            - mysql
        networks:
            - wordpress_mysql_network

    # phpmyadmin:
    #     image: phpmyadmin:latest
    #     container_name: phpmyadmin-wordpress
    #     ports:
    #         - "4283:80"
    #     environment:
    #         PMA_HOST: mysql_wordpress
    #         MYSQL_ROOT_PASSWORD: 1234
    #     depends_on:
    #         - mysql

networks:
    wordpress_mysql_network:
        driver: bridge
