version: '3.8'
services:
  app:
    image: php:8-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  nginx:
    image: nginx
    ports:
      - "8080:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    #   - .:/var/www
